### ISSUE TITLE
npm start 안되는 문제

### ISSUE THREAD

**Issue by khskys0805** [Hanium2023-WeB/starD-frontend#20]
font-awesome을 사용하려고 설치하는데 계속 오류가 떠서 지피티한테 물어보고 알려준대로 하다가 지금 npm start까지 안되는 지경까지 와버려서 도움 요청합니다...

현재 npm start를 하면
![image](https://github.com/Hanium2023-WeB/starD-frontend/assets/75068753/7f4d0a65-a46e-446a-a741-9abc19fa9af5)
이렇게 오류가 나는 상태여서 리액트 버전을 16으로 낮추려고 시도를 해봐도
![image](https://github.com/Hanium2023-WeB/starD-frontend/assets/75068753/8b280661-c5ca-4d58-8158-1ab3d97cd993)
마지막에 계속 저렇게 오류가 나는 상태입니다

지피티한테 물어보니까 캐시를 지우고 npm install을 다시 설치하거나 node_modules를 삭제후 재설치하라고 하는데 분리된 이후에 node_modules가 없고 npm install을 하면
![image](https://github.com/Hanium2023-WeB/starD-frontend/assets/75068753/73c87601-9e79-4c1f-9a2a-b7f52b32b06d)
이 오류가 또 나요..! 뭔가 버전이 충돌인거 같은데 잘 모르겠어요..
그래서 지금 몇시간 째 계속 무한 반복되는 느낌이라 도움 요청해요 어떻게 해결해야 실행이 될까요....

**Comment by rosieisor** [comment]
package.json 파일에 37번째 줄

`"proxy": "https://openapi.naver.com"`

이 부분 주석 처리한 상태로 해보시겠어요?!

**Comment by khskys0805** [comment]
헉 그거 하고 뭐 어찌저찌 다시 다 설치하고 하다보니까 해결이 된거같아요 감사합니다!!!
