### ISSUE TITLE
스터디 중단 요청사항

### ISSUE THREAD

**Issue by ckdmstn** [Hanium2023-WeB/starD-frontend#26]
1. 디자인 변경 (마음대로 변경하셔도 됩니다! 싹 갈아 엎으셔도 상관X.. 그냥 임의로 해둔 거라서요)

2. 버튼 삭제 -> 문자열 입력창으로 변경
> ![image](https://github.com/Hanium2023-WeB/starD-frontend/assets/77821089/7b786b5d-7c0d-42ff-ada0-dad06c49ddf1)

3. 스터디 중단되었을 때 todo, 일정, 채팅, 팀 커뮤니티 등 post를 막는다든지 뭔가 변화가 있어야 할 것 같아요!
> - 팀블로그 메인 화면에 중단된 스터디라는 표시도 추가?

![image](https://github.com/Hanium2023-WeB/starD-frontend/assets/77821089/dd8b42bf-0298-41ea-9880-b3635760f2d4)

**Comment by MinCodeHub** [comment]
구현완료
